name: TONPix Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Her 5 dakikada bir çalıştır
    - cron: '*/5 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TON_WALLET_ADDRESS: ${{ secrets.TON_WALLET_ADDRESS }}
        NODE_ENV: production
      run: |
        # Bot'u 5 dakika çalıştır, sonra durdur
        timeout 300 npm start || true 